variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
    SolutionBaseName: 'DFC.App.CareerPath'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v2.0.1
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

jobs:

#Build and test resources
- job: BuildArmTemplates
  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)

#Build and test application
- job: BuildDotNetCore
  displayName: Build-DotNetCore
  steps:
  # Build DFC.App.CareerPath
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-sonar.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      PublishWebApp: true
      TestSuffix: UnitTests

  #Build integration tests
- job: BuildIntegrationTests
  displayName: Build integration tests
  steps:
  # Build all Integration Tests that end with .IntegrationTests
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).IntegrationTests
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)


  # Build DFC.App.CareerPath.MessageFunctionApp
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName).MessageFunctionApp
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      PublishWebApp: true